development:
  default:
    queue: rabbit
    host: localhost:5672
  enable: true
test:
  default:
    queue: rabbit
    host: localhost:5672
  enable: true
production:
  default:
    queue: rabbit
    host: localhost:5672
  enable: true
