#!/usr/bin/env ruby

puts "Loading Rails..."
require File.dirname(__FILE__) + '/../config/environment'

if ARGV.include?('-d')
  ARGV.delete('-d')
  ARGV.unshift('start') unless ARGV.include?('stop')
  SweatShop.daemonize
else
  puts "Listening for new tasks..."
  SweatShop.complete_all_tasks
end
