#!/usr/bin/env ruby

if ARGV.include?('-d')
  ARGV.delete('-d')
  ARGV.unshift('start') unless ARGV.include?('stop')

  root = File.expand_path(File.dirname(__FILE__) + '/..')
  ARGV << "--rails=#{root}"

  system("ruby #{root}/vendor/gems/sweat_shop/lib/sweat_shop/sweatd.rb #{ARGV.join(' ')}")
else
  puts "Loading Rails..."
  require File.dirname(__FILE__) + '/../config/environment'
  puts "Listening for new tasks..."
  SweatShop.do_all_tasks
end
